name: build
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3.13.0
        with:
          java-version: '8'
          distribution: 'corretto'
      - name: Run protolock status step if .protolock exists
        run: |
          if [ -f proto.lock ]; then
            echo "protolock status check"
            ./protolock/protolock status --protoroot=./bankdemo/
          fi
      - name: Build packages
        run: ./gradlew buildAndCopy