name: build

on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'corretto'
      - name: Run protolock status step if proto.lock file exists
        run: |
          if [ -f proto.lock ]; then
            echo "Protolock status check"
            wget https://github.com/nilslice/protolock/releases/download/v0.16.0/protolock.20220302T184110Z.linux-amd64.tgz
            tar -zxvf protolock.20220302T184110Z.linux-amd64.tgz
            ./protolock status --protoroot=./bankdemo
          fi
      - name: Build packages
        run: ./gradlew buildAndCopy