name: build
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-java@v3.8.0
        with:
          java-version: '8'
          distribution: 'corretto'
      - name: Build packages
        run: ./gradlew buildAndCopy