name: reviewdog
on: [pull_request]
jobs:
  linter_name:
    name: runner / protolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yoheimuta/action-protolint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: error
          protolint_flags: -config_path=.protolint.yaml