name: Publish bank-demo-api packages
on:
 workflow_dispatch:
 
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-java@v3.8.0
        with:
          java-version: '8'
          distribution: 'corretto'
      - name: Build packages
        run: ./gradlew buildAndCopy --stacktrace
      - name: Publish Kotlin gRPC api
        run: ./gradlew publish --stacktrace
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ secrets.USERNAME }}
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@arvgord'
      - run: npm i
        working-directory: ./npm-package
      - name: Publish Typescript gRPC api
        run: npm publish
        working-directory: ./npm-package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}