name: Publish bank-demo-api packages

on:
 workflow_dispatch:
 
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'corretto'
      - name: Build packages
        run: ./gradlew buildAndCopy --stacktrace
      - name: Publish Kotlin gRPC API
        run: ./gradlew publish --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@arvgord'
      - name: Publish bank-demo-client gRPC API
        run: |
          cd ./npm_package
          npm i
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}