name: Publish bank-demo-api
on:
 workflow_dispatch:
 
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.5.0
      - uses: actions/setup-java@v3.8.0
        with:
          java-version: '8'
          distribution: 'corretto'
      - name: Publish to Github Packages
        run: ./gradlew publish --stacktrace
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ secrets.USERNAME }}