name: Publish bank-demo-api packages
on:
 workflow_dispatch:
 
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3.13.0
        with:
          java-version: '8'
          distribution: 'corretto'
      - name: Build packages
        run: ./gradlew buildAndCopy --stacktrace
      - name: Publish Kotlin gRPC API
        run: ./gradlew publish --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@arvgord'
      - run: npm i
        working-directory: ./npm_package
      - name: Publish Typescript gRPC API
        run: npm publish
        working-directory: ./npm_package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}